// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _2._2.Models;

public partial class Unit
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int StudentId { get; set; }

    public virtual Student Student { get; set; }
}